### ISSUE TITLE
timer dynamically starts and stops for board

### ISSUE THREAD

**Issue by fo0** [fo0/ScrumTool#24]

**Comment by DRU-CW** [comment]
and to have it running in the tab like https://www.timer-tab.com/

**Comment by fo0** [comment]
Implementation done. 
But there are some styling or component updates needed.

![image](https://user-images.githubusercontent.com/11175093/83401761-d5fada00-a405-11ea-9401-9e76457d45eb.png)

The component needs to change to a clock or s.th. like  this.

features
- synchronized timer for all users (start/stop are synchronized)
- start
- stop

pending
- timer to browser tab caption @KaesDingeling 
- another component for visualization, something like a clock with other interation button @KaesDingeling

**Comment by DRU-CW** [comment]
Please also add a pause button or for example that you click on the running time and the time stops.
