### ISSUE TITLE
multiple likes per card

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#27]
It is important, that you can give "likes" multiple times per card. (Background, if in your eyes something is really important you can push your item.

**Comment by fo0** [comment]
I would implement the it as a board option, something like
- allow multiple likes: `- <counter> +`

does this match with your request?

**Comment by fo0** [comment]
can be configured now via board-options
![image](https://user-images.githubusercontent.com/11175093/83361351-a35ecc00-a388-11ea-9107-275ecef17da9.png)
