### ISSUE TITLE
reset button for "likes" on board

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#28]
It would be nice, if you can reset your placed "likes" withour erasing the card, for example if you misclicked, or someone is explaining it in detail and you change your mind.

A button for resetting all likes would be enough.

**Comment by fo0** [comment]
added the button

![image](https://user-images.githubusercontent.com/11175093/83413276-dc944c00-a41b-11ea-8794-b34754dce903.png)
