### ISSUE TITLE
extend save time of board for 7 days

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#29]
It is also important that the save time per board is at least 7 days by default, in case you were not able to export it on time and also add an disclaimer, that it will be deleted after 7 days

**Comment by fo0** [comment]
the deletion function is not inside the app, that means its a simple cron-job (linux scheduler) which deletes the data when you want.

**Comment by fo0** [comment]
check out the readme: https://github.com/fo0/ScrumTool/blob/master/README.md
