### ISSUE TITLE
creation of cards - order

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#36]
when you create a card, the card should be always on top of the column, as many times you create a card and then see on the last minute that something was wrong, but you already have submitted it. Then currently you must scroll down to the end of the column to find it. And even use the scrollbeam

**Comment by fo0** [comment]
added and can be configured at in the create options of the board

![image](https://user-images.githubusercontent.com/11175093/84577988-4ec44380-adc1-11ea-82f4-f70618419018.png)


![image](https://user-images.githubusercontent.com/11175093/84577975-36542900-adc1-11ea-80a2-8f2da458db1e.png)
