### ISSUE TITLE
 message box for deleting columns

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#37]
In case you want to delete a column, please create a message box, before submitting:

Are you sure to delete this column? 

X Cancel                          y Delete

Otherwise people will delete the column and also all the cards are gone. Please give the users time to think :)

**Comment by fo0** [comment]
I added the confirm dialog but changed the button position to be more sure the user knows what he confirms.

![image](https://user-images.githubusercontent.com/11175093/84577174-4288b800-adba-11ea-86a1-8427314a923c.png)
