### ISSUE TITLE
make the timer design consistent with all other fields

### ISSUE THREAD

**Issue by DRU-CW** [fo0/ScrumTool#49]
the timer does not fit the design of the other fields. Please make it look the same.

in additon if you start the timer, the font of the numbers are changing to a larger font. please make them look the same as before.

in addtion the tooltips for the timer are 3 in total.
please delete the tooltip for the watch when you go over with the mouse. so in total we have 2 tooltips.

**Comment by fo0** [comment]
- [x] removed tooltip
- [x using same font size in the whole timer component
